### ISSUE TITLE
Failed to apply plugin [id 'com.google.gms.google-services']    > For input string: "+"

### ISSUE THREAD

**Issue by JaganJonnala** [nickcoury/nativescript-maps-app#5]
![image](https://user-images.githubusercontent.com/10844009/28150697-ace4a93e-67b3-11e7-8972-458a89325686.png)

**Comment by nickcoury** [comment]
It looks like your `firebase` plugin is conflicting with the version of Google Maps used with the Google Maps SDK plugin.  See [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#includegradle-failed-to-apply-plugin--for-input-string-).

**Comment by JaganJonnala** [comment]
Thanks lot,
Error fixed but map loading and all working fine but my map showing like this
![image](https://user-images.githubusercontent.com/10844009/28162086-88e48e5c-67e3-11e7-8ce0-b75c8d22708e.png)

**Comment by nickcoury** [comment]
Did you register and input your Google Developer API key?

**Comment by JaganJonnala** [comment]
yes i have done with it..

**Comment by JaganJonnala** [comment]
its working fine now @nickcoury .. Thank you ..
Changed new api key from google
